src/inet/applications/sctpapp/SCTPServer.cc
src/inet/transportlayer/contract/sctp/SCTPSocket.h

The changes in SCTPSocket.h fix a bug, that prevented the client to get the established notification and send data. 
The other commits helps to get rid of some undisposed messages

Sctp bugfixes

---

src/inet/physicallayer/common/Radio.cc

Without removal a SEGFAULT is caused in RadioMedium::computeMaxSpeed for dynamic radios, e.g. those controlled via TraCIScenarioManager

fix: remove radio from medium at destruction

---

src/inet/common/serializer/sctp/SCTPSerializer.cc

SACK and NR_SACK have to be handled separately because otherwise you get wrong results for numDups.
Also: getBitLength()/8 has been substituted by getByteLength()

Handle SACK and NR_SACK separately

---

src/run_inet

OS X is case insensitive and the -x matched the inet directory

fix: failed to start the examples on MAC OS X.

---

src/inet/networklayer/ipv6/IPv6.cc

This fixes a problem that I experienced when compiling with a custom feature configuration without xMIPv6
Best regards
Till

Fixes compiler error when compiling feature IPv6 without feature xMIPv6

---

src/inet/networklayer/ipv6/IPv6RoutingTable.cc
src/inet/networklayer/pim/modes/PIMBase.cc
src/inet/networklayer/pim/modes/PIMBase.h
src/inet/networklayer/pim/modes/PIMSM.cc

Sorry, this only came up when I started testing with OS X on our jenkins!
Same Issue as previous pull request
Second commit fixes an issue that came up in our windows jenkins slave: See also https://groups.google.com/forum/#!topic/inetframework-contrib/mPweUaLIlyg
Best Till

Implementation is required for IPv6 feature and cannot be disabled when xMIPv6 is disabled.

---

.oppfeatures
src/inet/common/serializer/ipv6/IPv6Serializer.cc

Hi everyone!
We build net only with wired physical layer. This fixes a dependency problem when ieee80211 is disabled.
Best regards
Till

fixes build without ieee80211

---

src/inet/common/Compat.h

Please check if it is ok to use NAMESPACE macros in inet.

compat.h: check_and_cast should be defined in optional omnetpp namespace not in inet!

---

src/inet/applications/netperfmeter/NetPerfMeter.cc
src/inet/applications/netperfmeter/NetPerfMeter.h
src/inet/applications/netperfmeter/NetPerfMeter.ned
src/inet/applications/netperfmeter/NetPerfMeterHost.ned

A couple of fixes and improvements for the NetPerfMeter model:
- Fixes and code clean-ups for bidirectional data transfer
- UDP fixes
- On/off behaviour is now working like for the real application (https://www.uni-due.de/~be0001/netperfmeter/)
- Added Pareto distribution as NED function, since it is very convenient for modelling background traffic. This may be realized in a better way, e.g. by moving to OMNeT++ directly.

Integration netperfmeter updates 11mar2015

---

src/inet/transportlayer/sctp/SCTPAssociationBase.cc

ccFunctions.ccUpdateBeforeSack needs to be initialised with &SCTPAssociation::cwndUpdateBeforeSack. Otherwise, ccFunctions.ccUpdateBeforeSack is nullptr, and the call to this function will fail.

CC function initialisation bugfix: need to initialise function to call before SACK

---

src/applications/httptools/HttpServerBase.cc

The size of resources sent when using random mode (i.e., non-scripted mode) does not match the size configured by the user. This commit fix that.

Set the correct size for resources in random browsing mode.

---

src/transport/rtp/RTCP.cc
src/transport/rtp/RTPParticipantInfo.cc
src/transport/rtp/RTPParticipantInfo.h

The string returned by `RTPParticipantInfo::ssrcToName()` is dynamically allocated using `opp_strdup()`, but none of the callers release it. To fix that and avoid future memory leaks, I've changed the result type from `char*` to `std::string` so that the release is handled automatically.

Fix a memory leak with the result of RTPParticipantInfo::ssrcToName()

---

src/transport/rtp/profiles/avprofile/RTPAVProfilePayload32Sender.cc

This commit fixes multiple things:
* the parsing of GDF files which only detects space characters as correct fields separators. All the example GDF files use tabulations as separators, so the parsing does not work correctly even for official examples (the type of video frames is wrongly parsed).
* there's a mistake between bits and bytes when computing the size of MPEG packets. The quantities in GDF files are in bits, but they are converted to bytes before the splitting loop.
* the payload size of MPEG packets is never set while the RTP receiver needs it.
With this commit, the RTP examples work correctly now...

Fix parsing and units in RTPAVProfilePayload32Sender::sendPacket().

---

src/transport/udp/UDP.cc

The control info associated with UDP packet is removed from it when receiving an undeliverable packet. It and the packet is then given to `UDP::processUndeliverablePacket()`, but this method only releases the packet (which does not release the control info since it is not associated with the packet anymore). The calls to `sendErrorMessage()` (icmp/icmpv6) do not release the control info either, so there's a memory leak.
I don't know if the control info should be released in `UDP::processUndeliverablePacket()` or in `sendErrorMessage()`, but it must be released anyway. I choose the former for this commit.
I'm really surprised that no one has ever found that leak in the past as OMNet++ runs out of memory quickly when using UDP broadcast/multicast streaming, which does not sound like an …

Fix a memory leak when handling undeliverable UDP packets.

---

src/mobility/common/MobilityBase.cc

This commit allows the initial positions of nodes (set in omnetpp.ini) to contain non-integer values, and to show the exact positions of nodes in the UI instead of rounding them to nearest integer positions. The UI is already able to handle non-integer positions so why would the mobility module try to feed it with only integer positions?
By integer positions I mean position where `x` and `y` are integers.
Please, consider merging this commit in inet.

Allow initial positions to contain non-integer values.

---

src/transport/rtp/RTPPayloadReceiver.cc
src/transport/rtp/RTPPayloadReceiver.ned
src/transport/rtp/profiles/avprofile/RTPAVProfilePayload32Receiver.cc

The RTP log files are generated automatically by the `RTPPayloadReceiver` modules, 2 for each nodes. When simulating lots of nodes, you end up with lots of files even if you are not interested by their content.
This commit permits to disable the generation of these files based on the user configuration.
Please consider merging it into the inet framework.

Allow the user to disable RTP logging to file.

---

src/inet/applications/netperfmeter/NetPerfMeter.cc

Some debug code got merged that set frameSize=1424 when frameSize=0 (i.e. no transmission) was configured => unwanted data transmissions. Fixed this by removing the debug code.

Fix: removed debug code that caused unwanted data transmissions.

---

Makefile

I frequently do static builds instead of shared object builds. Therefore, I just moved the opp_makemake options into a separate options line and added another build target "makefiles-static" for the static build. So, creating a static build can be done with "make makefiles-static && make". The old behaviour as default remains unchanged (i.e. shared-object builds with "make makefiles && make").

Added target "makefiles-static" to Makefile => easy static builds

---

src/inet/transportlayer/sctp/SCTPAssociationEventProc.cc

The queue size limit was only checked for ordered messages. Consequently, no limitation was done for unordered ones.

Bugfix: Also send SCTP_I_SENDQUEUE_FULL indication for unordered messages

---

src/inet/transportlayer/contract/sctp/SCTPSocket.h

sctp: added default parameter settings to connect() call of SCTPSocket. Then, in the usual case, a connect() just takes address and port (like it is for TCP).

sctp: added default parameter settings to connect() call of SCTPSocket

---

src/inet/transportlayer/contract/sctp/SCTPSocketMap.cc
src/inet/transportlayer/contract/sctp/SCTPSocketMap.h

sctp: Added SCTPSocketMap class, in the same way as it is provided with TCPSocketMap for TCP. This makes developing TCP/SCTP applications easier (since they can both use a similar API).

sctp: Added SCTPSocketMap class, in the same way as it is provided with TCPSocketMap for TCP. 

---

src/inet/transportlayer/contract/sctp/SCTPCommand.msg
src/inet/transportlayer/contract/sctp/SCTPSocket.cc
src/inet/transportlayer/contract/sctp/SCTPSocket.h
src/inet/transportlayer/sctp/SCTP.cc
src/inet/transportlayer/sctp/SCTPAssociation.h
src/inet/transportlayer/sctp/SCTPAssociationBase.cc
src/inet/transportlayer/sctp/SCTPAssociationEventProc.cc
src/inet/transportlayer/sctp/SCTPAssociationUtil.cc

sctp: Fixed wrong usage of cPacket by replacing with cMessage.

sctp: Fixed wrong usage of cPacket by replacing with cMessage

---

src/inet/transportlayer/contract/sctp/SCTPSocket.cc

sctp: Two fixes in SCTPSocket:
1. Call bind(0) on unbound socket before connect. Otherwise, the local side will have an empty list of local addresses -> segfault in SCTPAssociation::process_ASSOCIATE().
2. Without explicitly setting the number of inbound and outbound streams, the corresponding variables remain uninitialized -> failures during run. Found this bug with Valgrind.

sctp: "connect without bind" bugfixes

---

src/inet/transportlayer/sctp/SCTPAssociationRcvMessage.cc

After "sctpMain->removeAssociation(this);", a return is necessary. Otherwise, the not-any-longer-existing association will cause a segfault due to access to already-free'd memory at the end of the method.

sctp: Bugfix for SCTPAssociation::process_RCV_Message():

---

src/inet/transportlayer/contract/sctp/SCTPSocket.cc

sctp: Bugfix: SCTPSocket::send() may send a message in unordered mode *only* if its kind is SCTP_C_SEND_UNORDERED. In any other case, use ordered mode as default.

SCTPSocket bugfix for ordered/unordered mode selection

---

src/inet/transportlayer/sctp/SCTPAssociationSendAll.cc

sctp: Bugfix for SACK Immediately option:
Removed wrong "if" clause that caused to not set the I-bit when necessary.

SACK Immediately fix: removed wrong "if" clause.

---

src/inet/common/ModuleAccess.h

I'm sorry this pops up right after the 3.0 release!
We saw a problem when including ModuleAccess.h under Windows due to the way the INET_API Macro works:
13:40:42 In file included from applications/api/AS6802/CoRE4INET_TTEAPIApplicationBase.cc:25:0:
13:40:42 ../../inet/src/inet/common/ModuleAccess.h:66:13: error: function 'T* inet::findModuleFromPar(cPar&, cModule)' definition is marked dllimport
13:40:42 INET_API T *findModuleFromPar(cPar& par, cModule *from)
13:40:42 ^
13:40:42 In file included from applications/api/AS6802/CoRE4INET_TTEAPIApplicationBase.cc:25:0:
13:40:42 ../../inet/src/inet/common/ModuleAccess.h:88:13: error: function 'T inet::getModuleFromPar(cPar&, cModule*)' definition is marked dllimport
13:40:42 INET_API T *getModuleFromPar(cPar& par, cModule *from)
This patch …

Fixes Windows build error when including ModuleAccess.h

---

src/inet/transportlayer/tcp/TCP.ned
src/inet/transportlayer/tcp/TCPConnectionUtil.cc

@rhornig 
To make the window scale factor configurable helps to compare the simulation to TCP stacks where you can set the factor via sysctl.

TCP: Configurable window scale factor

---

src/inet/common/serializer/headerserializers/arp/ARPSerializer.h
src/inet/common/serializer/headerserializers/ethernet/EthernetSerializer.h
src/inet/common/serializer/ipv4/ICMPSerializer.h
src/inet/common/serializer/ipv4/IGMPSerializer.h
src/inet/common/serializer/ipv4/IPv4Serializer.h
src/inet/common/serializer/ipv6/ICMPv6Serializer.h
src/inet/common/serializer/ipv6/IPv6Serializer.h
src/inet/common/serializer/sctp/SCTPSerializer.h
src/inet/common/serializer/tcp/TCPSerializer.h
src/inet/common/serializer/udp/UDPSerializer.h

This fixes the "undefined reference to vtable" problem under windows.
I'm not completely in the picture with all this INET_API thing, but it seems like it is recently often forgotten in new code. Is there a way we can prevent these problems?

Added INET_API Macro to serializers

---

src/inet/applications/httptools/common/HttpNodeBase.cc

The HttpNodeBase did not use the defined delay of it's configuration file.

Fixed unsed delay in sendDirectToModule()

---

src/inet/networklayer/ipv4/ICMP.cc

Hi,
I found that when creating ICMP Echo Replys, inet would simply reuse the old IPv4ControlInfo from the request with swapped SRC and DST addresses.
This means that the packet would be sent with the TTL it has seen on the request packet. 
By setting it to 0, the IPv4 layer correctly resets it to the default TTL.
Best,
Julius

fixed invalid TTL reuse for ICMP Echo Reply

---

src/inet/linklayer/ieee80211/mac/channelaccess/Edcaf.cc

Bug: Edcaf always takes the fallback value from getAifsNumber(ac) instead of the aifsn parameter when given.

Edcaf: fix aifs calculation for customised aifsn

---

src/inet/physicallayer/ieee802154/packetlevel/Ieee802154NarrowbandScalarRadio.ned

In the past, there has been confusion regarding the `bandwith` parameter of _Ieee802154NarrowbandScalarRadio_.
In the current form, the module is unusable because the default bandwith of _0.25 MHz_ does not even satisfy the assert in [DSSSOQPSK16Modulation.cc:42](https://github.com/inet-framework/inet/blob/master/src/inet/physicallayer/modulation/DSSSOQPSK16Modulation.cc#L42).
This is related to the issue discussed in the commit 
[e062cb7c7d0c5c10eedf154f303ad692ba1ba458](https://github.com/inet-framework/inet/commit/e062cb7c7d0c5c10eedf154f303ad692ba1ba458).
Later, the BER calculation in _DSSSOQPSK16Modulation.cc_ was fixed but the required change to _Ieee802154NarrowbandScalarRadio_ has not been merged, leading to the current incompatibility.
This pull request would introduce the …

Fixing Ieee802154NarrowbandScalarRadio

---

src/inet/physicallayer/apskradio/packetlevel/APSKScalarReceiver.cc
tests/module/APSKScalarRadio_Sensitivity.test

The `APSKScalarReceiver` is using the `NarrowbandReceiverBase` to determine whether a reception is possible. This is only checking whether the carrier frequency and bandwidth are equal. The `FlatReceiverBase` has a more advanced check whether a reception is possible by checking against the `sensitivity` parameter of the receiver.
I changed the call to the parent module and added a test that checks whether the `sensitivity` is considered when deciding if a reception is gonna be attempted.
Let me know what you think!

consider sensitivity for computeIsReceptionPossible in APSKScalarReceiver

---

src/inet/linklayer/ieee802154/Ieee802154Mac.cc

Queue frames were inserted even the queue length had
been reached already. This error reduced the number
of queue drops and increased the performance.
Reviewed-by: Florian Kauer <florian.kauer@koalo.de>

Fixed erroneous CSMA queue length check

---

src/inet/physicallayer/ieee802154/packetlevel/Ieee802154NarrowbandScalarRadioMedium.ned

For FreeSpacePathLoss, the carrierFrequency of mediumLimitCache is required.
Signed-off-by: Florian Kauer <florian.kauer@koalo.de>

Ieee802154: Add carrierFrequency to mediumLimitCache

---

inet_featuretool

Before, calling inet_featuretool repair without the submodules
showcases and tutorial checked out lead to a failure and the
repair action was aborted. Since both submodules are VERY large
and are often not required, this commit avoids the failure
so it is not required to download these submodules.

featuretool: Do not fail if submodules are not checked out

---

src/inet/physicallayer/common/packetlevel/Radio.cc

Corrected a fatal bug in the radio module that can occur if the separateReceptionParts mode is used.
This fixes an invalid delete(void*) attempt that occurs if a packet reception ends while the radio is still switching from RX --> another mode. Previously the code was trying to use abortReception(cMessage*) on a packet that had already been processed with endReception(cMessage*). If your simulation was unlucky enough to encounter this case the simulator would segfault.

bugfix: corrected memory management issue in radio module

---

src/inet/routing/aodv/Aodv.cc
src/inet/routing/aodv/Aodv.h
src/inet/routing/aodv/Aodv.ned

The user can set/unset the D flag in a RREQ message through the destinationOnlyFlag parameter. It is 'false' by default meaning that an intermediate route can respond to a RREQ message if it has a fresh route to the destination. If 'destinationOnlyFlag ' is 'true' then the intermediate node will not respond to the RREQ (even if it has a valid fresh route to the destination), and forwards the RREQ message. Here is the output log of a sample scenario:
aodvRouter5 is an intermediate node that receives a RREQ message with D flag set, thus it will forward the message.

aodv: responding properly to the D (destination only flag) flag

---

src/inet/linklayer/ieee802154/Ieee802154Mac.cc
src/inet/linklayer/ieee802154/Ieee802154Mac.ned

The retry limit is for a different purpose than the backoff limit for CSMA/CA in IEEE 802.15.4 so they should be tracked separately. I think CONGESTION matches the case of a channel that was sensed busy several times very good. An alternative would be to add a BACKOFF_LIMIT_REACHED.

Use CONGESTION instead of RETRY_LIMIT_REACHED for backoff limit reached

---

src/inet/common/Topology.cc
src/inet/common/Topology.h
src/inet/networklayer/configurator/base/NetworkConfiguratorBase.cc
src/inet/networklayer/configurator/base/NetworkConfiguratorBase.h
src/inet/networklayer/configurator/base/NetworkConfiguratorBase.ned
src/inet/networklayer/configurator/ipv4/Ipv4NetworkConfigurator.cc
src/inet/networklayer/configurator/ipv4/Ipv4NetworkConfigurator.h

IPv4 configurator builds a topology from the network and uses that topology to assign IPv4 addresses to each interface. Imagine the following scenario that consists of two isolated networks: These two networks are completely detached from each other, but the topology class detect it as a single big network. This means that the IPv4 addresses assigned to the second isolated network (on the bottom) will be the continuation of the first network (on the top).
In some scenarios, the user wants to treat these two networks isolated and expects the IPv4 addresses to be completely independent from each other. This commit adds a new parameter to the IP configurator called `configureEachGroupSeparatly`. If it is set to true, then the IPv4 addresses are assigned like the following:
The topology class …

Ipv4config: isolated networks can be configured separately

---

src/inet/physicallayer/pathloss/TwoRayInterference.cc
src/inet/physicallayer/pathloss/TwoRayInterference.h
src/inet/physicallayer/pathloss/TwoRayInterference.ned

I have revisited my initial port (from Veins to INET) of the TwoRayInterference path loss model. It can handle now vertical as well as horizontal antenna polarization. Furthermore, I believe it is far more readable now due to restructured code and a lot more comments.

improve implementation of TwoRayInterference path loss

---

examples/wireless/nic/omnetpp.ini
src/inet/common/Protocol.cc
src/inet/common/Protocol.h
src/inet/linklayer/ieee80211/Ieee80211Interface.ned
src/inet/linklayer/ieee80211/llc/Ieee80211EtherTypeHeader.msg
src/inet/linklayer/ieee80211/llc/Ieee80211EtherTypeHeaderSerializer.cc
src/inet/linklayer/ieee80211/llc/Ieee80211EtherTypeHeaderSerializer.h
src/inet/linklayer/ieee80211/llc/Ieee80211EtherTypeProtocolDissector.cc
src/inet/linklayer/ieee80211/llc/Ieee80211EtherTypeProtocolDissector.h
src/inet/linklayer/ieee80211/llc/Ieee80211EtherTypeProtocolPrinter.cc
src/inet/linklayer/ieee80211/llc/Ieee80211EtherTypeProtocolPrinter.h
src/inet/linklayer/ieee80211/llc/Ieee80211Llc.h
src/inet/linklayer/ieee80211/llc/Ieee80211Llc.ned
src/inet/linklayer/ieee80211/llc/Ieee80211LlcEpd.cc
src/inet/linklayer/ieee80211/llc/Ieee80211LlcEpd.h
src/inet/linklayer/ieee80211/llc/Ieee80211LlcEpd.ned
src/inet/linklayer/ieee80211/llc/Ieee80211LlcLpd.cc
src/inet/linklayer/ieee80211/llc/Ieee80211LlcLpd.h
src/inet/linklayer/ieee80211/llc/Ieee80211LlcLpd.ned
src/inet/linklayer/ieee80211/llc/LlcProtocolTag.msg
src/inet/linklayer/ieee80211/mac/Ieee80211Mac.cc
src/inet/linklayer/ieee80211/mac/Ieee80211Mac.h
src/inet/linklayer/ieee80211/mac/Ieee80211MacProtocolDissector.cc
src/inet/linklayer/ieee80211/mac/coordinationfunction/Dcf.cc
src/inet/linklayer/ieee80211/mac/coordinationfunction/Hcf.cc
src/inet/linklayer/ieee80211/portal/Ieee80211Portal.h
src/inet/linklayer/ieee80211/portal/Ieee80211Portal.ned

According to E.2.3/E.2.4 of IEEE 802.11-2016, stations in the 5.9 GHz band have to use "EtherType Protocol Discrimination" (EPD) instead of IEEE 802.2 (LPD) commonly used for other bands. Unfortunately, there is no packet field to differentiate them so a `LlcProtocolTag` is added to each packet for dissecting both variants seamlessly. If this tag is missing and there is no information available about the employed band, it falls back to IEEE 802.2.

ieee80211: support EtherType protocol discrimination in 5.9 GHz band

---

src/inet/physicallayer/ieee802154/packetlevel/Ieee802154NarrowbandDimensionalRadioMedium.ned

The analog model of the Ieee802154NarrowbandDimensionalRadioMedium was not set, thus it inherited the default from RadioMedium, which is a scalar model.

802.15.4: Set analog model of Ieee802154NarrowbandDimensionalRadioMedium to DimensionalAnalogModel

---

src/inet/linklayer/ieee80211/mac/channelaccess/Edca.cc

Pull request for v3.6.7-bis.
This seems to be necessary at least since OMNeT++ 5.6 to keep deleteModule() of a parent module from failing.

use deleteModule() to delete cSimpleModule

---

src/inet/queueing/scheduler/PriorityScheduler.cc
src/inet/queueing/scheduler/PriorityScheduler.h
src/inet/queueing/scheduler/PriorityScheduler.ned

For example in the IEEE 802.1Q standard's multi-queues, queue priorities are in descending order. So I think it makes sense to support inverse priorities in INET's PriorityScheduler module to be able to easily recreate such queuing networks while retaining the queue indizes given in these standards.

queuing: Allow inverse priorities for PriorityScheduler

---

examples/ethernet/gatepreemption/GatePreemptionExample.ned
examples/ethernet/gatepreemption/omnetpp.ini
src/inet/protocol/server/PreemptingServer.ned
src/inet/queueing/base/PacketGateBase.cc
src/inet/queueing/base/PacketGateBase.ned

Fixes packets streams not getting interrupted when packet gates close. Also adds an example simulation for frame preemption in combination with packet gates.

Fix packet gates and add example simulation for frame preemption based on gate events

---

src/inet/physicallayer/antenna/CosineAntenna.cc
src/inet/physicallayer/antenna/DipoleAntenna.cc
src/inet/physicallayer/antenna/ParabolicAntenna.cc

When simulating satellite networks, we observed the problem that the antenna gain is falling to 0 randomly due to small calculation errors in the dot product because of the large values in the position vectors. (getting absolute values slightly larger than 1)
This was only prevented in the AxiallySymmetricAntenna, thus for this pull request the implementation from the AxiallySymmetricAntenna is just copied to the other antenna classes where a acos is used.

fix: Prevent acos in antenna classes getting nan

---

src/inet/physicallayer/wireless/common/radio/packetlevel/Radio.cc

This only occurs in very specific scenarios where:
* Reception has started
* The radio mode has begun switching, but not completed switching.
* The signal ends and `endReception` is called. But since the radio is now in the switching mode, the if statement on https://github.com/inet-framework/inet/blob/bbf2ef9cd8eb59271527cde549c5e9994f36df43/src/inet/physicallayer/wireless/common/radio/packetlevel/Radio.cc#L474 is false.
* The  timer object is deleted https://github.com/inet-framework/inet/blob/bbf2ef9cd8eb59271527cde549c5e9994f36df43/src/inet/physicallayer/wireless/common/radio/packetlevel/Radio.cc#L491 but `receptionTimer` variable still points to a deallocated section.
* The `completeRadioModeSwitch` calls `abortReception(receptionTimer)` which tries to access the deleted object.

Bugfix: Segfault when accessing receptionTimer after endReception

---

src/inet/physicallayer/wireless/common/radio/packetlevel/Radio.cc

Example that revealed problem:
1) Radio transmission from neighbour active on medium
2) Radio is commanded (e.g. from Mac layer) to receive mode, switching begins
3) Active transmission from neighbour ends and `endReception(timer)` is called
4) `updateTransceiverState()` determines `RECEPTION_STATE_BUSY` or `RECEPTION_STATE_IDLE`
5) Emits incorrect `receptionStateChangedSignal` and `transmissionStateChangedSignal`

Bugfix to prevent wrong ...StateChangedSignal when Switching

---

src/inet/common/clock/ClockUserModuleMixin.h
src/inet/common/clock/ClockUserModuleMixinImpl.h

In OMNeT++ 6.0 preview 9 the rescheduleAt and rescheduleAfter methods have been added to cSimpleModule. It might be a good idea to also add these methods to the ClockModuleMixin for a more consistent API.

Clock: Add methods for rescheduling events

---

src/inet/protocolelement/common/InterpacketGapInserter.cc

Clock time is accessed before clock is initialized.

Fix InterpacketGapInserter

---

src/inet/linklayer/ethernet/common/MacRelayUnit.cc
src/inet/linklayer/ieee8021d/relay/Ieee8021dRelay.cc

If we don't carry over user priorities (from IEEE802.1Q tag) in the relay unit, they'll get lost.

RelayUnit: Consider user priority

---

examples/htb/omnetpp.ini
examples/htb/tree_scenario1Eth.xml
examples/htb/tree_scenario2Eth.xml
examples/htb/tree_scenario2PrioEth.xml
examples/htb/tree_scenarioPrioEth.xml

In HTBQueue Example with Ethernet interface, the `HtbScheduler::htbDequeue()` method was throwing the error: "The class leafhostFDO0 deficit on level 0 is negative!"
This error occurred due to the "quantum" value in the HTB tree being set too low. What happens when this value is too low, is that the "deficit" controlling the Deficit Round Robin part of the scheduling algorithm (DRR prevents flow starvation) could never recover above 0. "Quantum" essentially governs how the deficit is replenished after a packet transmission. It needs to be set to a value greater or equal the maximum packet size (including all headers, also PHY). The misconfiguration meant that the given class would not be able to be selected for dequeue. Hence the check for deficit < 0 that threw the error.
The quantum was …

HTBQueue: Fix & add examples working with Ethernet interface

---

src/inet/common/packet/recorder/PcapngWriter.cc

Timestamp (High) and Timestamp (Low): upper 32 bits and lower 32 bits of a 64-bit timestamp. The timestamp is a single 64-bit unsigned integer that represents the number of units of time that have elapsed since 1970-01-01 00:00:00 UTC. The length of a unit of time is specified by the 'if_tsresol' option (see [Figure 10](https://www.ietf.org/staging/draft-tuexen-opsawg-pcapng-02.html#format_idb)) of the Interface Description Block referenced by this packet (Default: 10^-6). Note that, unlike timestamps in the libpcap file format, timestamps in Enhanced Packet Blocks are not saved as two 32-bit values that represent the seconds and microseconds that have elapsed since 1970-01-01 00:00:00 UTC. Timestamps in Enhanced Packet Blocks are saved as two 32-bit words that represent the upper and …

Fix PcapngWriter timestamps

---

src/inet/networklayer/common/NetworkInterface.h

Creating a custom network interface in an inet dependant project causes a linking error in `lld` on Windows.
This is because the vtable for the `NetworkInterface::LocalGate` is not exported into the DLL symbols list.

Fix missing `INET_API` in nested `NetworkInterface::LocalGate` with vtable

---

src/inet/linklayer/ethernet/LayeredEthernetInterface.ned

Without this parameter the ipv4 always assumes an infinite MTU when combined with the LayeredEthernetInterface.
Now its configurable with the Ethernet default MTU as the default value.

Fix missing MTU parameter in LayeredEthernetInterface

---

src/inet/common/packet/tag/SharingRegionTagSet.h
src/inet/common/packet/tag/SharingTagSet.h

Some methods in files SharingRegionTagSet.h and SharingTagSet.h were declared as inline, but in a way that the compiler doesn't like. Typically this leaded just to some warnings. However, third-party projects linking might fail because of that (as linker found duplicate symbols).
Resolves #778

inline mis-redeclaration fixed on two *TagSet.h files

---

src/inet/power/storage/CcBatteryPack.ned

Derives the `SimpleCcBattery` module to create an energy storage module that simulates a number of cells connected in a series or parallel arrangement.
Addresses issue: https://github.com/inet-framework/inet/issues/843

[SimpleCcBattery feature] Implement series battery pack module

---

src/inet/queueing/gate/PeriodicGate.cc

Switch schedule and processing of changeTimer within PeriodicGate::handleMessage.
This pull request should resolve issue #822.

[TSN bug] IEEE8021qTimeAwareShaper PeriodicGate did not check lenght of first packet

---

src/inet/common/ModuleAccess.h

Similarly to getModuleFromPar, provide a template method that takes care of dynamic casting.
Tested successfully.
I have followed the coding style, you might want to tweak the error messages.

Add getModuleSomewhereUp template method

---

src/inet/common/ProtocolGroup.cc
src/inet/common/ProtocolGroup.h

This commit assumes that every `Protocol` added with `ProtocolGroup::addProtocol` has been dynamically allocated (it admits as much in the comment).
Firstly, this assumption is simply wrong. It is perfectly possible to have a `Protocol` as a global variable. In this case, the destructor of the `ProtocolGroup` class attempts to free an address of the data segment, which produces an error at the end of a simulation ("free() : invalid pointer").
Secondly, this commit also assumes (implicitly this time) that a dynamically allocated `Protocol` hasn't already been freed by the time the destructor of `ProtocolGroup` is called, which turns out to be also wrong. If we transform our previous `Protocol` instantiated as a global variable in a dynamically allocated one, whose pointer is stored in a …

Revert "ProtocolGroup: deallocate dynamically added protocols in the destructor"

---

src/inet/common/packet/chunk/ByteCountChunk.cc

Just increasing the length of a ByteCountChunk when inserting a ByteCountChunk with different data leads to incorrect packets.
Example: Ethernet padding (PaddingInserter) with 0 when payload is also a ByteCountChunk with default 0x3f data.

Fix merging of two ByteCountChunks with different data

---

src/inet/linklayer/ieee8021q/ATSIeee8021qFilter.ned
src/inet/protocolelement/shaper/GroupEligibilityTimeMeter.cc
src/inet/protocolelement/shaper/GroupEligibilityTimeMeter.h
src/inet/protocolelement/shaper/GroupEligibilityTimeMeter.ned
src/inet/protocolelement/shaper/GroupEligibilityTimeTable.cc
src/inet/protocolelement/shaper/GroupEligibilityTimeTable.h
src/inet/protocolelement/shaper/GroupEligibilityTimeTable.ned

Current implementation of the ATS algorithm in EligibilityTimeMeter sets groupEligibilityTime per stream, this can break the FIFO order of packets in the switch (See: IEEE 802.1Qcr, Section 8.6.5.6 (NOTE 2), and Specht, J., and S. Samii, “Urgency-Based Scheduler for Time-Sensitive Switched Ethernet Networks,” 28th Euromicro Conference on Real-Time Systems (ECRTS), pp. 75–85, 2016. ) . 
This change introduces a ATSIeee8021qFilter with a setup of a GroupEligibilityTimeTable, GroupEligibilityTimeMeter, and EligibilityTimeFilter, to replace the current ATS setup using the EligibilityTimeMeter and EligibilityTimeFilter modules. 
Packets arriving at the GroupEligibilityTimeMeter are checked for their group (ingress port + priority), if there already is a groupEligibilityTime in the table, this …

asynchronous traffic shaper with scheduler groups

---

src/inet/queueing/gate/PeriodicGate.cc

When the offset of a PeriodicGate is negative, the state is inconsistent until the end of the first cycle, as the initialization phase is not executed properly.
This PR fixed this, by ensuring the modulo calculation for the offset always produces a positive result.

Fixed bug with negative offsets in PeriodicGate

---

showcases/tsn/trafficshaping/asynchronousshaper/doc/index.rst
src/inet/linklayer/ieee8021q/Ieee8021qAsynchronousShaper.ned
tests/validation/tsn/trafficshaping/asynchronousshaper/core4inet/omnetpp.ini
tests/validation/tsn/trafficshaping/asynchronousshaper/icct/omnetpp.ini

To me the ATS showcase description was quite confusing because it took me a while to figure out that the Ieee8021qAsynchronousShaper is exactly the same as the EligibilityTimeGate.
To this end, I added a comment in the NED file of the Ieee8021qAsynchronousShaper and consistently use the EligibilityTimeGate module in showcase descriptions and configurations.
For the cbsandats showcase I was usure what to do and decided to not change it as it helps here for clarification which queue uses which shaper.

Consistent use of EligibilityTimeGate and Ieee8021qAsynchronousShaper

---

src/inet/protocolelement/shaper/GroupEligibilityTimeMeter.h
src/inet/protocolelement/shaper/GroupEligibilityTimeMeter.ned
src/inet/protocolelement/shaper/GroupEligibilityTimeTable.ned

The class names for the GroupEligibilityTimeMeter and GroupEligibilityTimeTable in  PR #973 were wrong, which lead to errors trying to use the ATSIeee8021qFilter. 
This pull request fixes these class names.

Fix to asynchronous shaper with scheduler groups 
