- src/inet/applications/sctpapp/SCTPClient.cc
- src/inet/applications/sctpapp/SCTPClient.h
- src/inet/applications/sctpapp/SCTPNatPeer.cc
- src/inet/applications/sctpapp/SCTPNatPeer.h
- src/inet/applications/sctpapp/SCTPPeer.cc
- src/inet/applications/sctpapp/SCTPPeer.h
- src/inet/applications/sctpapp/SCTPPeer.ned
- src/inet/applications/sctpapp/SCTPServer.cc
- src/inet/common/serializer/sctp/SCTPSerializer.cc
- src/inet/transportlayer/sctp/SCTP.cc
- src/inet/transportlayer/sctp/SCTP.h
- src/inet/transportlayer/sctp/SCTPAssociation.h
- src/inet/transportlayer/sctp/SCTPAssociationAddIP.cc
- src/inet/transportlayer/sctp/SCTPAssociationBase.cc
- src/inet/transportlayer/sctp/SCTPAssociationEventProc.cc
- src/inet/transportlayer/sctp/SCTPAssociationRcvMessage.cc
- src/inet/transportlayer/sctp/SCTPAssociationSendAll.cc
- src/inet/transportlayer/sctp/SCTPAssociationUtil.cc
- src/inet/transportlayer/sctp/SCTPCCFunctions.cc
- src/inet/transportlayer/sctp/SCTPMessage.cc
- src/inet/transportlayer/sctp/SCTPMessage.h
- src/inet/transportlayer/sctp/SCTPMessage.msg
- src/inet/transportlayer/sctp/SCTPNatHook.cc
- src/inet/transportlayer/sctp/SCTPNatTable.cc
- src/inet/transportlayer/sctp/SCTPNatTable.h
- src/inet/transportlayer/sctp/SCTPReceiveStream.cc
- src/inet/transportlayer/sctp/SCTPSendStream.cc
- src/inet/transportlayer/sctp/SCTPSendStream.h
Coverity commits concerning SCTP, SCTP-APP and SCTPSerializer
> Sctp coverity

- src/transport/tcp/TCPConnectionUtil.cc
http://dev.omnetpp.org/bugs/view.php?id=810
> TCP scaling window patch

- src/inet/transportlayer/sctp/SCTP.cc
- src/inet/transportlayer/sctp/SCTPAssociationUtil.cc
sctp: Signed/unsigned warning fixes.
> sctp: Signed/unsigned warning fixes.

- src/linklayer/ethernet/EthernetInterface.ned
I have fixed a small mistake (probably a typo) in the code. Please check. Thanks!
> Fixed a small mistake

- src/inet/transportlayer/sctp/SCTPAssociationBase.cc
- src/inet/transportlayer/sctp/SCTPAssociationRcvMessage.cc
sctp: Bugfix: do not delete state->shutdownChunk twice.
> SCTP bugfix

- src/inet/applications/httptools/configurator/HttpController.cc
- src/inet/applications/httptools/configurator/HttpController.h
- src/inet/applications/httptools/server/HttpServerBase.cc
httptools: fixed registration of server when servers are inside other modules
> httptools: bugfix

- src/inet/linklayer/ethernet/EtherMAC.cc
- src/inet/linklayer/ethernet/EtherMAC.ned
- src/inet/linklayer/ethernet/EtherMACBase.cc
- src/inet/linklayer/ethernet/EtherMACBase.h
- src/inet/linklayer/ethernet/EtherMACFullDuplex.cc
- src/inet/linklayer/ethernet/EtherMACFullDuplex.ned
- src/inet/linklayer/ethernet/Ethernet.h
New pull request for master
It contains the changes for the issues: #160 , #162 and #163. If one of the changes is undesired you would have to git-cherry-pick.
**As there are changes in the statistics this might break fingerprints! So please have a careful look that I did not make a mistake! The module tests (eth*.test), were ok**
Best regards
Till
> Fixing/New Feature #160, #162 and 163 (EtherMAC)

- src/inet/common/serializer/SerializerBase.h
This PR fixes #186 
Requires review by serializer maintainer: This should be perfectly fine, but please doublecheck.
> fixes #186 by adding namespace to serializers

- src/inet/linklayer/csma/CSMA.cc
- src/inet/mobility/static/StaticConcentricMobility.cc
- src/inet/networklayer/contract/INetfilter.h
- src/inet/physicallayer/ieee802154/packetlevel/Ieee802154NarrowbandScalarRadio.ned
- src/inet/physicallayer/modulation/DSSSOQPSK16Modulation.cc
- src/inet/physicallayer/modulation/DSSSOQPSK16Modulation.h
- src/inet/routing/gpsr/GPSR.cc
- src/inet/routing/gpsr/GPSR.h
- src/inet/routing/gpsr/GPSR.ned
Several bug fixes related to IEEE 802.15.4 parts collected over the last months.
> IEEE 802.15.4 fixes

- src/inet/physicallayer/antenna/ConstantGainAntenna.cc
- src/inet/physicallayer/antenna/ConstantGainAntenna.h
- src/inet/physicallayer/antenna/CosineAntenna.cc
- src/inet/physicallayer/antenna/CosineAntenna.h
- src/inet/physicallayer/antenna/DipoleAntenna.cc
- src/inet/physicallayer/antenna/DipoleAntenna.h
- src/inet/physicallayer/antenna/InterpolatingAntenna.cc
- src/inet/physicallayer/antenna/InterpolatingAntenna.h
- src/inet/physicallayer/antenna/IsotropicAntenna.cc
- src/inet/physicallayer/antenna/IsotropicAntenna.h
- src/inet/physicallayer/antenna/ParabolicAntenna.cc
- src/inet/physicallayer/antenna/ParabolicAntenna.h
- src/inet/physicallayer/base/packetlevel/DimensionalAnalogModelBase.cc
- src/inet/physicallayer/base/packetlevel/PathLossBase.cc
- src/inet/physicallayer/base/packetlevel/ScalarAnalogModelBase.cc
- src/inet/physicallayer/base/packetlevel/TransmissionBase.cc
- src/inet/physicallayer/base/packetlevel/TransmissionBase.h
- src/inet/physicallayer/common/packetlevel/MediumLimitCache.cc
- src/inet/physicallayer/common/packetlevel/RadioMedium.cc
- src/inet/physicallayer/common/packetlevel/RadioMedium.h
- src/inet/physicallayer/common/packetlevel/Signal.cc
- src/inet/physicallayer/contract/packetlevel/IAntenna.h
- src/inet/physicallayer/contract/packetlevel/IAntennaGain.h
- src/inet/physicallayer/contract/packetlevel/IRadioMedium.h
- src/inet/physicallayer/contract/packetlevel/ITransmission.h
- src/inet/physicallayer/pathloss/TwoRayGroundReflection.cc
- src/inet/physicallayer/pathloss/TwoRayInterference.cc
- src/inet/visualizer/base/MediumVisualizerBase.cc
- src/inet/visualizer/physicallayer/MediumCanvasVisualizer.cc
Fixing dangling transmitter radio pointer of #250. This pull requests represents a revised version #262 targeting the integration branch.
> IAntennaGain integration

- src/inet/linklayer/xmac/XMacFrame.msg
- src/inet/linklayer/xmac/XMacLayer.cc
- src/inet/linklayer/xmac/XMacLayer.h
- src/inet/linklayer/xmac/XMacLayer.ned
This is the implementation of Joaquim Oller for the MiXiM framework that I ported to INET as a part of my bachelor thesis.
It is useful in the context of wireless sensor network simulations when considering low power listening protocols.
> Added implementation of the X-MAC linklayer protocol

- src/inet/applications/netperfmeter/NetPerfMeter.cc
- src/inet/applications/sctpapp/SctpClient.cc
- src/inet/common/figures/CounterFigure.cc
- src/inet/common/figures/LinearGaugeFigure.cc
- src/inet/common/figures/PlotFigure.cc
- src/inet/common/figures/QueueFigure.cc
- src/inet/physicallayer/apskradio/bitlevel/ApskDecoder.cc
> fix a few (annoying) compile warnings

- bin/inet
- src/inet/visualizer/scene/SceneOsgEarthVisualizer.cc
- src/inet/visualizer/scene/SceneOsgEarthVisualizer.h
- src/makefrag
And a minor tweak in the `bin/inet` script.
> Fix build if OSG is available, but osgEarth isn't (contains the patch in #353)

- src/inet/applications/tcpapp/TcpSessionApp.cc
the numBytes is missed in the debug info
> Fix the debug info print

- src/inet/routing/rip/Rip.cc
[commit 863ea16]
According to RIP RFC, the cost of a directly-connected interface in RIP is 1. The RIPConfig has a cool attribute, `metric`, that allows users to change the default cost of an interface. However, this feature has not been tested extensively in INET because in some scenarios it might throw run-time error. For example, try to run Step11 in the following scenario:
https://github.com/ManiAm/inet/blob/INETex/examples_INETex/routing_protocol_rip/omnetpp.ini
The following line causes this error:
https://github.com/inet-framework/inet/blob/ce5150cef349c3cddf969dab694c8dc8cd930089/src/inet/routing/rip/Rip.cc#L879
The fix does not affect any of the previous scenarios (+fingerprints). It fixes the above issue caused by non-default metric.
[commit 8a8cb7f]
Some implementations (such …
> RIP improvements - round 2

- src/inet/linklayer/ieee8021d/rstp/Rstp.cc
- src/inet/linklayer/ieee8021d/stp/Stp.cc
I fixed (from ERROR to FAIL) at least some of the RSTP specific tests from /examples/ieee8021d/ but `STP-LinkReconnect`still ERRORs.
> Screw topic/inet4 for ansa

- src/inet/networklayer/contract/IRoute.cc
- src/inet/networklayer/ipv4/Igmpv2.cc
- src/inet/networklayer/ipv4/Igmpv2.h
- src/inet/networklayer/ipv4/Igmpv3.cc
- src/inet/networklayer/ipv4/Igmpv3.h
- src/inet/routing/pim/PimSplitter.cc
- src/inet/routing/pim/modes/PimBase.cc
- src/inet/routing/pim/modes/PimBase.h
- src/inet/routing/pim/modes/PimDm.cc
- src/inet/routing/pim/modes/PimDm.h
- src/inet/routing/pim/modes/PimSm.cc
- src/inet/routing/pim/modes/PimSm.h
- src/inet/routing/pim/tables/PimInterfaceTable.cc
- src/inet/routing/pim/tables/PimNeighborTable.cc
Fingerprints are all intact :)
Update: I finally fix my local master. No more garbage commits.
Step by step examples for multi-casting (in progress)
https://github.com/ManiAm/inet/blob/INETex3/examples_INETex/multicasting/omnetpp.ini
> IGMP and PIM improvements

- src/inet/common/Protocol.cc
- src/inet/common/Protocol.h
- src/inet/common/ProtocolGroup.cc
- src/inet/common/Simsignals.cc
- src/inet/common/Simsignals.h
I added Protocol and signals definitions for CLNS and IS-IS.
> Adding support for IS-IS and CLNS

- src/inet/applications/udpapp/UdpBasicApp.cc
- src/inet/applications/udpapp/UdpBasicApp.h
- src/inet/applications/udpapp/UdpBasicApp.ned
This allows to create scenarios such as this:
https://github.com/ManiAm/inet/blob/eca5f4c9f77514a6f00f4d53e9ba8dec73970c7c/examples_INETex/ICMP/omnetpp.ini#L82
> udpBasicApp: adding dontFragment param

- examples/htb/configs/baseQoS/router_htbEvalI.xml
- examples/htb/evaluationsHtb.ned
- examples/htb/htbEvaluation.ini
- examples/htb/tree_scenario1.xml
- examples/htb/tree_scenario2.xml
- examples/htb/tree_scenario2Prio.xml
- examples/htb/tree_scenarioPrio.xml
- src/inet/linklayer/ppp/Ppp.h
- src/inet/queueing/classifier/HtbClassifier.cc
- src/inet/queueing/classifier/HtbClassifier.h
- src/inet/queueing/classifier/HtbClassifier.ned
- src/inet/queueing/queue/HtbQueue.ned
- src/inet/queueing/scheduler/HtbScheduler.cc
- src/inet/queueing/scheduler/HtbScheduler.h
- src/inet/queueing/scheduler/HtbScheduler.ned
Licensing potentially not final
HtbClassifier unchanged -> pending removal
> Added current version of the HtbQueue

- examples/htb/omnetpp.ini
- tests/fingerprint/examples.csv
Sorry for no updates recently. We finally found some time to update the fingerprint tests with proper simulation times. Of course, we verified that all interesting things happen within the new, shorter, simulation time for the examples.
Note that we used the "~tND" argument instead of the "tyf" argument. The "Fake GUI" which got used originally with the "tyf" argument made the whole simulation fail on our machines. We were using Omnetpp-6.0pre12. That said, it works with the "~tND" argument.
Any feedback is welcome!
> Fine-tuned HTB fingerprint tests and example simulations

- src/inet/visualizer/scene/SceneOsgEarthVisualizer.cc
- src/inet/visualizer/scene/SceneOsgEarthVisualizer.h
> Inet 3.8.3 update 2 files

- src/inet/linklayer/ieee8021q/Ieee8021qFilter.ned
- src/inet/linklayer/ieee8021q/SimpleIeee8021qFilter.ned
- src/inet/queueing/filter/BackPressureBasedFilter.cc
- src/inet/queueing/filter/BackPressureBasedFilter.h
- src/inet/queueing/filter/BackPressureBasedFilter.ned
> Change behavior of Ieee8021qFilter and SimpleIeee8021qFilter to match the Qci standard
